# Sample Dockerfile

# Some commemt
FROM somthing/weird:foo

# Another comment
LABEL maintainer="me@example.com"

# Next comment
RUN echo "Hello World - Dockerfile" > ~/file.txt

# Run command
CMD [ "cmd" ]